name = "Cherry Marmalade"
description = "Feeding filthy bops to fancy-faced fops!"
keywords = "Cherry Marmalade, music band, prog rock, metal, Pune"
image = "_logo.png"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-Q0W5K8WD1X"
base_url = "https://raagaception.github.io/cherrymarmaladeofficial"

[[sections]]
title = "Links"
description = "Keep up with our work on our socials!"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "YouTube"
description = "Check out our recent live performances"
url = "https://www.youtube.com/@CherryMarmaladeOfficial"
[[sections.items]]
title = "Instagram"
description = "Fow band pictures, and music release updates"
url = "https://www.instagram.com/cherrymarmaladeofficial"
