name = "Cherry Marmalade"
description = "Fancy-faced fops, feeding you filthy bops!"
keywords = "Cherry Marmalade, music band, prog rock, metal, Pune"
image = "_Logov5.jpeg"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-Q0W5K8WD1X"
base_url = "https://raagaception.github.io/cherrymarmaladeofficial"

[[sections]]
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/mEL7IbCxiH0"

[[sections]]
title = "Socials"
description = "Keep up with our work on these websites!"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/cherrymarmaladeofficial"
[[sections.items]]
icon = "https://cdn.simpleicons.org/youtube/ffffff"
title = "YouTube"
url = "https://www.youtube.com/@CherryMarmaladeOfficial"
